const DATABASE_NAME = '@criptomemoria';

//@app:collection

const COLLECTION_EASY_CLASSIC = `${DATABASE_NAME}:easyClassic`;
const COLLECTION_MEDIUM_CLASSIC = `${DATABASE_NAME}:mediumClassic`;
const COLLECTION_HARD_CLASSIC = `${DATABASE_NAME}:hardClassic`;

const CLASSIC_CURRENT_LEVEL = `${DATABASE_NAME}:ClassicCurLevel`;
const FRENETIC_CURRENT_LEVEL = `${DATABASE_NAME}:FreneticCurLevel`;

const COLLECTION_EASY_FRENETIC = `${DATABASE_NAME}:easyFrenetic`;
const COLLECTION_MEDIUM_FRENETIC = `${DATABASE_NAME}:mediumFrenetic`;
const COLLECTION_HARD_FRENETIC = `${DATABASE_NAME}:hardFrenetic`;

export {
  COLLECTION_EASY_CLASSIC,
  COLLECTION_MEDIUM_CLASSIC,
  COLLECTION_HARD_CLASSIC,
  CLASSIC_CURRENT_LEVEL,
  COLLECTION_EASY_FRENETIC,
  COLLECTION_MEDIUM_FRENETIC,
  COLLECTION_HARD_FRENETIC,
  FRENETIC_CURRENT_LEVEL,
}